version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: guessing-game-db
    environment:
      POSTGRES_DB: guessing_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guessing-game-network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: guessing-game-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - guessing-game-network

networks:
  guessing-game-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
