package com.example.Immobi.Dto.game;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Author: QuanNH
 * Response DTO for number guessing game results
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GuessResponse {
    /**
     * Whether the guess was correct
     */
    private boolean correct;
    
    /**
     * The number generated by the system
     */
    private int generatedNumber;
    
    /**
     * The number guessed by the player
     */
    private int guessedNumber;
    
    /**
     * Number of turns remaining for the player
     */
    private int remainingTurns;
    
    /**
     * Current score of the player
     */
    private int score;
    
    /**
     * Result message to display to the player
     */
    private String message;
} 